image: Visual Studio 2017

environment:
  matrix:
    - TARGET_ARCH: "x64"
      MINICONDA: "C:\\Miniconda35-x64"
      MYCONDAPY: 3.5
    - TARGET_ARCH: "x64"
      MINICONDA: "C:\\Miniconda36-x64"
      MYCONDAPY: 3.6
    - TARGET_ARCH: "x64"
      MINICONDA: "C:\\Miniconda37-x64"
      MYCONDAPY: 3.7
      
build: off

platform:
    - x64
    
init:
    - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%MINICONDA%\\Library\\bin;%PATH%"

install:
    - conda config --set always_yes true --set changeps1 no
    #- conda config --add channels metgem
    
    - conda install -q conda conda-build conda-verify anaconda-client
    - conda create -q -n test-env python=%MYCONDAPY%   
    - activate test-env
    - conda install numpy setuptools cython
    - pip install pyteomics pytest pylint pytest-pylint pytest-cov codecov

test_script:
    - python setup.py build_ext --inplace --with-cython-coverage --force
    - python setup.py develop
    - pytest --pylint --pylint-rcfile=.pyrcfile --pylint-error-types=EF libmetgem
    - pytest tests --cov=libmetgem
    
after_test:
    # Upload the coverage analysis
    - codecov -e PYTHON=%MYCONDAPY%